### ISSUE TITLE
Stats issue with tp to lobby

### ISSUE THREAD

**Issue by SESOSUS** [Yannici/bedwars-reloaded#1045]
I have the problem on the latest version of the plugin that the plugin dont teleport a player back when statistics are enabled
spigot: spigot-1.8.8-R0.1-SNAPSHOT-latest

**Comment by SESOSUS** [comment]
I saw that a error accured now: 

java.lang.NullPointerException
	at io.github.bedwarsrel.statistics.PlayerStatisticManager.storeYamlStatistic(PlayerStatisticManager.java:329) ~[?:?]
	at io.github.bedwarsrel.statistics.PlayerStatisticManager.storeStatistic(PlayerStatisticManager.java:321) ~[?:?]
	at io.github.bedwarsrel.game.Game.playerLeave(Game.java:1313) ~[?:?]
	at io.github.bedwarsrel.game.SingleGameCycle.kickPlayer(SingleGameCycle.java:32) ~[?:?]
	at io.github.bedwarsrel.game.SingleGameCycle.onGameEnds(SingleGameCycle.java:71) ~[?:?]
	at io.github.bedwarsrel.game.SingleGameCycle.onGameOver(SingleGameCycle.java:136) ~[?:?]
	at io.github.bedwarsrel.game.GameOverTask.run(GameOverTask.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
	
i think there should be a saving yml for the statics but it doesnt create itself so maybe thats the issue at all
