### ISSUE TITLE
Bedwars-Rel report errors

### ISSUE THREAD

**Issue by xinghan1** [Yannici/bedwars-reloaded#1062]
I had a problem configuring the bed station

statistics:
  enabled: true
  show-on-game-end: true
  storage: database
  bed-destroyed-kills: true
  scores:
    kill: 2
    die: 0
    win: 20
    bed-destroy: 25
    lose: 0
    record: 10
  player-leave-kills: true

As long as I change this configuration to true, an error will be reported in the background

[18:05:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedwarsRel v1.3.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_321]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]
Caused by: java.lang.NullPointerException
        at io.github.bedwarsrel.statistics.PlayerStatisticManager.loadDatabaseStatistic(PlayerStatisticManager.java:185) ~[?:?]
        at io.github.bedwarsrel.statistics.PlayerStatisticManager.loadStatistic(PlayerStatisticManager.java:227) ~[?:?]
        at io.github.bedwarsrel.statistics.PlayerStatisticManager.getStatistic(PlayerStatisticManager.java:114) ~[?:?]
        at io.github.bedwarsrel.game.Game.playerJoins(Game.java:922) ~[?:?]
        at io.github.bedwarsrel.commands.JoinGameCommand.execute(JoinGameCommand.java:65) ~[?:?]
        at io.github.bedwarsrel.utils.BedwarsCommandExecutor.onCommand(BedwarsCommandExecutor.java:55) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        ... 15 more
I had a problem configuring the bed station

**Comment by andriycraft** [comment]
The plugin is abonded and no longer supported

**Comment by RangeBanenge** [comment]
Use Screaming Bedwars, it's the same plugin only for new versions.
