### ISSUE TITLE
BedWarsRel bug command /bw itemspaste

### ISSUE THREAD

**Issue by RangeBanenge** [Yannici/bedwars-reloaded#1063]
BedWarsRel
Error help URGENT!, when entering the command /bw itemspaste
the link to the chat is not displayed, an error is displayed in the console.
[16:51:29 WARN]: java.io.IOException: Server returned HTTP response code: 401 for URL: https://hastebin.com/documents
[16:51:29 WARN]: at sun.net.[www.protocol.http.HttpURLConnection.getInputStream0(Unknown](http://www.protocol.http.httpurlconnection.getinputstream0%28unknown/) Source)
[16:51:29 WARN]: at sun.net.[www.protocol.http.HttpURLConnection.getInputStream(Unknown](http://www.protocol.http.httpurlconnection.getinputstream%28unknown/) Source)
[16:51:29 WARN]: at sun.net.[www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown](http://www.protocol.https.httpsurlconnectionimpl.getinputstream%28unknown/) Source)
[16:51:29 WARN]: at io.github.bedwarsrel.utils.HastebinUtility.upload(HastebinUtility.java:35)
[16:51:29 WARN]: at io.github.bedwarsrel.commands.ItemsPasteCommand$1.run(ItemsPasteCommand.java:62)
[16:51:29 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[16:51:29 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[16:51:29 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:51:29 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:51:29 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:51:29 WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by RangeBanenge** [comment]
Use Screaming Bedwars, it's the same plugin only for new versions.
