### ISSUE TITLE
Console Errors (with default config)

### ISSUE THREAD

**Issue by helptiger** [Yannici/bedwars-reloaded#18]
[10:23:02 INFO]: [Bedwars] Enabling Bedwars v0.1.0
[10:23:02 ERROR]: Cannot load plugins/Bedwars/config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 45, column 1:
    	
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:188) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at io.github.yannici.bedwarsreloaded.Main.loadLocalization(Main.java:78) [BedWarsReloaded%202.jar:?]
	at io.github.yannici.bedwarsreloaded.Main.onEnable(Main.java:60) [BedWarsReloaded%202.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:273) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:226) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:287) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommands.onCommand(PlugManCommands.java:100) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 45, column 1:
    	
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	... 24 more
[10:23:02 ERROR]: [Bedwars] Cannot load configuration from jar
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 45, column 1:
    	
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:214) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at io.github.yannici.bedwarsreloaded.Main.loadLocalization(Main.java:78) [BedWarsReloaded%202.jar:?]
	at io.github.yannici.bedwarsreloaded.Main.onEnable(Main.java:60) [BedWarsReloaded%202.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:273) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:226) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:287) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommands.onCommand(PlugManCommands.java:100) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 45, column 1:
    	
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	... 21 more
[10:23:02 INFO]: [Bedwars] Game "towers" successfully loaded!

**Comment by Granik24** [comment]
Are you tried to restart server? This is caused by PlugMan, sometimes, i have this problem too.

**Comment by Yannici** [comment]
You used a tab in the configuration. Tabs are not allowed in .yml files! Or is this the default configuration?

**Comment by Yannici** [comment]
All tabs were removed in commit https://github.com/Yannici/bedwars-reloaded/commit/9a985dcb8ac0fee79a930c197d06eaf03eb44754
