### ISSUE TITLE
Console Errors (with tabs removed from config.yml)

### ISSUE THREAD

**Issue by helptiger** [Yannici/bedwars-reloaded#19]
[10:28:16 INFO]: [Bedwars] Enabling Bedwars v0.1.0
[10:28:16 WARN]: [Bedwars] Could not save de.yml to plugins/Bedwars/locale/de.yml because de.yml already exists.
[10:28:16 WARN]: [Bedwars] Could not save cz.yml to plugins/Bedwars/locale/cz.yml because cz.yml already exists.
[10:28:16 WARN]: [Bedwars] Could not save en.yml to plugins/Bedwars/locale/en.yml because en.yml already exists.
[10:28:16 ERROR]: [Bedwars] Cannot load configuration from jar
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 45, column 1:
    	
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:214) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at io.github.yannici.bedwarsreloaded.Main.loadLocalization(Main.java:78) [BedWarsReloaded.jar:?]
	at io.github.yannici.bedwarsreloaded.Main.onEnable(Main.java:60) [BedWarsReloaded.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 45, column 1:
    	
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	... 15 more
[10:28:16 INFO]: [Bedwars] Spiel "towers" wurde erfolgreich geladen!

**Comment by Yannici** [comment]
All tabs were removed in commit https://github.com/Yannici/bedwars-reloaded/commit/9a985dcb8ac0fee79a930c197d06eaf03eb44754
