### ISSUE TITLE
Spiel startet nicht und Team nicht wählbar

### ISSUE THREAD

**Issue by megadampfnudel** [Yannici/bedwars-reloaded#226]
Habe das Plugin heute auf meinen Server geladen und konfiguriert. Danach wollte ich es mit einem Freund testen und als wir gejoint sind konnte wir keine Team wählen und die Zeit blieb bei 60 Sekunden stehen.
Fehlermeldung n der Konsole:
[10:47:02 ERROR]: Could not pass event InventoryClickEvent to BedwarsRel v1.2.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-1646]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-1646]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [minecraft_server.jar:git-Spigot-1646]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1477) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:15) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(PacketPlayInWindowClick.java:65) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [minecraft_server.jar:git-Spigot-1646]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1646]
Caused by: java.lang.IllegalArgumentException: Player list names can only be a maximum of 16 characters long
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:193) ~[minecraft_server.jar:git-Spigot-1646]
	at io.github.yannici.bedwars.Game.Team.addPlayer(Unknown Source) ~[?:?]
	at io.github.yannici.bedwars.Listener.PlayerListener.onLobbyInventoryClick(Unknown Source) ~[?:?]
	at io.github.yannici.bedwars.Listener.PlayerListener.onInventoryClick(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_10]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_10]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_10]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_10]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[minecraft_server.jar:git-Spigot-1646]
	... 13 more

**Comment by Yannici** [comment]
"teamname-on-tab" auf "false" stellen. Das geht bei 1.7 nicht. Ist bei der nächsten Version gefixt.
