### ISSUE TITLE
VillagerShop console error when click on catergory item

### ISSUE THREAD

**Issue by helptiger** [Yannici/bedwars-reloaded#24]
[17:19:09 WARN]: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.server.v1_8_R1.EntityVillager.by to java.lang.Integer
[17:19:09 WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[17:19:09 WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[17:19:09 WARN]: 	at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(UnsafeBooleanFieldAccessorImpl.java:86)
[17:19:09 WARN]: 	at java.lang.reflect.Field.set(Field.java:758)
[17:19:09 WARN]: 	at io.github.yannici.bedwarsreloaded.Com.v1_8_R1.VillagerItemShop.createVillager(VillagerItemShop.java:41)
[17:19:09 WARN]: 	at io.github.yannici.bedwarsreloaded.Com.v1_8_R1.VillagerItemShop.access$0(VillagerItemShop.java:36)
[17:19:09 WARN]: 	at io.github.yannici.bedwarsreloaded.Com.v1_8_R1.VillagerItemShop$1.run(VillagerItemShop.java:68)
[17:19:09 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:19:09 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[17:19:09 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709)
[17:19:09 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[17:19:09 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[17:19:09 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[17:19:09 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:19:09 WARN]: java.lang.NullPointerException
[17:19:09 WARN]: 	at io.github.yannici.bedwarsreloaded.Com.v1_8_R1.VillagerItemShop$1.run(VillagerItemShop.java:72)
[17:19:09 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:19:09 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[17:19:09 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709)
[17:19:09 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[17:19:09 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[17:19:09 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[17:19:09 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Yannici** [comment]
Fixed with commit: https://github.com/Yannici/bedwars-reloaded/commit/7f951e776153796a4ba14f89b93e3b37f9850909
