### ISSUE TITLE
Bungeecord Zurück zum HUB server funktioniert nicht!

### ISSUE THREAD

**Issue by logtainment** [Yannici/bedwars-reloaded#251]
Hallo,
ich habe bei diesem Plugin Bungeecord konfiguriert. Wenn man in der Game Lobby ist und auf Leave drückt kommt folgendes in der Konsole:
[04:09:28 WARN]: [BedwarsRel] Task #194 for BedwarsRel v1.2.5 generated an exception
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:482) ~[spigot_server.jar:git-Spigot-d97e08b-5e85956]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1039) ~[spigot_server.jar:git-Spigot-d97e08b-5e85956]
        at io.github.yannici.bedwars.Game.BungeeGameCycle$6.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-d97e08b-5e85956]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot_server.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_server.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot_server.jar:git-Spigot-d97e08b-5e85956]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot_server.jar:git-Spigot-d97e08b-5e85956]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

Aber man kommt nicht auf den HUB Server zurück.
Hier die Config:

bungeecord:
  enabled: true
  hubserver: lobby
  spigot-restart: false
  motds:
    lobby: '&a[Lobby]'
    running: '&1[Running]'
    stopped: '&c[Stopped]'
    full: '&c[Full]'

**Comment by Yannici** [comment]
Du hast Bungeecord nicht aktiv. D.h. der Server auf dem Bedwars läuft ist nicht in der Bungeecord-Farm. Er findet den Kommunikationschannel "BungeeCord" nicht. Das hat also nichts mit meinem Plugin zu tun, sondern mit deiner Server-Administration.

**Comment by logtainment** [comment]
Okay wie kann ich das ändern? Aber über den Lobbyserver kann man /server bw machen
