### ISSUE TITLE
Protection wall error

### ISSUE THREAD

**Issue by piter909** [Yannici/bedwars-reloaded#282]
[10:26:46] [Server thread/WARN]: java.lang.IllegalArgumentException: The width of a protection block has to be odd!
[10:26:46] [Server thread/WARN]: 	at io.github.yannici.bedwars.Shop.Specials.ProtectionWall.create(Unknown Source)
[10:26:46] [Server thread/WARN]: 	at io.github.yannici.bedwars.Shop.Specials.ProtectionWallListener.onInteract(Unknown Source)
[10:26:46] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[10:26:46] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:26:46] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[10:26:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
[10:26:46] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:26:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
[10:26:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
[10:26:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:382)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:662)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[10:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by piter909** [comment]
Spigot 1649, java 7

**Comment by piter909** [comment]
protection-wall:
    break-time: 0
    wait-time: 20
    can-break: true
    item: BRICK
    block: SANDSTONE
    width: 4
    height: 4
    distance: 2

**Comment by Yannici** [comment]
"The width of a protection block has to be odd!"
Set width to "5" and it will work ;)

**Comment by piter909** [comment]
It was a default vaule, I did not change it in past :x.
You should fix it
