### ISSUE TITLE
Hologramme in version 1.2.7

### ISSUE THREAD

**Issue by DaNeo61** [Yannici/bedwars-reloaded#290]
Ich spiele derzeit mal beta user xD, 
und ich habe folgenden fehler

[19:58:57 INFO]: DaNeo issued server command: /bw addholo
[19:58:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedwarsRel v1.2.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f94fe8f-219686b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f94fe8f-219686b]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-f94fe8f-219686b]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NullPointerException
        at io.github.yannici.bedwars.Commands.AddHoloCommand.execute(Unknown Source) ~[?:?]
        at io.github.yannici.bedwars.BedwarsCommandExecutor.onCommand(Unknown Source) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f94fe8f-219686b]
        ... 15 more

**Comment by DaNeo61** [comment]
Den Fehler hab ich behoben in dem ich HolographicDisplays als standtalone eingefügt!
Allerdigns werden die Stats überlappend angezeigt werden von den jeweiligen spielern in der Lobby

**Comment by Yannici** [comment]
Dann brauchst du ProtocolLib!

**Comment by brainscript** [comment]
@DaNeo61 SInnlos "Hallo Yannici" in den Titel zu packen ... :pig_nose:
