### ISSUE TITLE
Shop fehler

### ISSUE THREAD

**Issue by HobbyzockerLP** [Yannici/bedwars-reloaded#302]
Habe in der shop.yml einen Fehler gemacht. Aber diesen Fehler finde ich nicht!
Shop.yml: http://pastebin.com/aiiNq5GK

**Comment by Yannici** [comment]
Ich denke es liegt daran, dass du den Text `Trage diese Schuhe und erhalte 40%` so schreiben solltest: `"Trage diese Schuhe und erhalte 40%"`.
Ansonsten ist dieser Issue Tracker nicht für Anwenderfehler geeignet!

**Comment by HobbyzockerLP** [comment]
Geht immer noch nicht... :(

**Comment by yannickko** [comment]
Die Bindestriche bei name müssen weg
    name: "Rüstung"
Zu
    name: Rüstung

**Comment by yannickko** [comment]
Oder? @Yannici

**Comment by HobbyzockerLP** [comment]
[00:10:41 INFO]: [BedWars] Couldn't load shop! Error in parsing shop!
[00:10:41 WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character          '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 228, column 14:
          reward:
                 ^

[00:10:41 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[00:10:41 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
[00:10:41 WARN]:        at io.github.yannici.bedwars.Main.loadShop(Unknown Source)
[00:10:41 WARN]:        at io.github.yannici.bedwars.Commands.ReloadCommand.execute(Unknown Source)
[00:10:41 WARN]:        at io.github.yannici.bedwars.BedwarsCommandExecutor.onCommand(Unknown Source)
[00:10:41 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:10:41 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:10:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[00:10:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(CraftServer.java:632)
[00:10:41 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:405)
[00:10:41 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:369)
[00:10:41 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[00:10:41 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[00:10:41 WARN]:        at java.lang.Thread.run(Thread.java:745)
[00:10:41 WARN]: Caused by: while scanning for the next token
found character          '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 228, column 14:
          reward:
                 ^

[00:10:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
[00:10:41 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[00:10:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
[00:10:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[00:10:41 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:132)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:200)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[00:10:41 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[00:10:41 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
[00:10:41 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
[00:10:41 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:400)
[00:10:41 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[00:10:41 WARN]:        ... 13 more

**Comment by yannickko** [comment]
Zumindest sind in der Default Config auch keine

**Comment by HobbyzockerLP** [comment]
@yannickko nein

**Comment by HobbyzockerLP** [comment]
Zeile 228 waren ein paar Leerzeichen, die ich nicht gemacht habe... habe nur enter gedrückt um unter den reward einen namen für das item hinzuschreiben.

**Comment by yannickko** [comment]
(Do not use \t(TAB) for indentation)

Sagt alles

**Comment by Yannici** [comment]
Alle Sonderzeichen müssen innerhalb von Hochkommata (" ") stehen, also auch Umlaute wie äöü!
Und natürlich nur Leerzeichen und keine TABs ;)
