### ISSUE TITLE
1.9 support

### ISSUE THREAD

**Issue by deltaflyer4747** [Yannici/bedwars-reloaded#443]
bedwars-rel loads with this:

[06:53:44 INFO]: [BedwarsRel] Enabling BedwarsRel v1.2.8
[06:53:44 INFO]: [BedWars] Couldn't find version related class io.github.yannici.bedwars.Com.v1_9_R1.TNTSheepRegister
[06:53:44 WARN]: java.lang.NullPointerException
[06:53:44 WARN]:        at io.github.yannici.bedwars.Shop.Specials.TNTSheepListener.<init>(Unknown Source)
[06:53:44 WARN]:        at io.github.yannici.bedwars.Shop.Specials.SpecialItem.loadSpecials(Unknown Source)
[06:53:44 WARN]:        at io.github.yannici.bedwars.Main.registerListener(Unknown Source)
[06:53:44 WARN]:        at io.github.yannici.bedwars.Main.onEnable(Unknown Source)
[06:53:44 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[06:53:44 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[06:53:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[06:53:44 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[06:53:44 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[06:53:44 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[06:53:44 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[06:53:44 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[06:53:44 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[06:53:44 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522)
[06:53:44 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by sebastianbinder** [comment]
Right now, BedwarsRel is supporting Minecraft versions 1.7.X and 1.8.X

**Comment by Yannici** [comment]
1.9 will be supported soon.

**Comment by sebastianbinder** [comment]
@Yannici It already has been released and I'm currently have a look on it with dropping 1.7 and adding 1.9 support. But this time I really might need your help there….
