### ISSUE TITLE
Error with 1.9 spigot at shutdown

### ISSUE THREAD

**Issue by HydroTekZ** [Yannici/bedwars-reloaded#496]
[18:53:31] [Thread-10/WARN]: Exception in thread "Thread-10" 
[18:53:31] [Thread-10/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[18:53:31] [Thread-10/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:400)
[18:53:31] [Thread-10/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123)
[18:53:31] [Thread-10/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:106)
[18:53:31] [Thread-10/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:89)
[18:53:31] [Thread-10/WARN]: 	at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:32)
[18:53:31] [Thread-10/WARN]: 	at io.github.yannici.bedwars.Updater.PluginUpdater.runUpdater(PluginUpdater.java:866)
[18:53:31] [Thread-10/WARN]: 	at io.github.yannici.bedwars.Updater.PluginUpdater.access$100(PluginUpdater.java:51)
[18:53:31] [Thread-10/WARN]: 	at io.github.yannici.bedwars.Updater.PluginUpdater$UpdateRunnable.run(PluginUpdater.java:841)
[18:53:31] [Thread-10/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by sebastianbinder** [comment]
Hi. Is that one reproducible or did that happen just once?
