### ISSUE TITLE
Console spam while playing 

### ISSUE THREAD

**Issue by helptiger** [Yannici/bedwars-reloaded#53]
[18:35:10 WARN]: net.minecraft.server.v1_8_R1.ExceptionWorldConflict: The save for world located at ./bw_goldrush is being accessed from another location, aborting
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:72)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.World.checkSession(World.java:2786)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:131)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:249)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:357)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.WorldServer.doTick(WorldServer.java:221)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:756)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[18:35:10 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:35:10 WARN]: net.minecraft.server.v1_8_R1.ExceptionWorldConflict: The save for world located at ./bw_goldrush is being accessed from another location, aborting
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:72)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.World.checkSession(World.java:2786)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:131)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:249)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:357)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.WorldServer.doTick(WorldServer.java:221)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:756)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[18:35:10 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:35:10 WARN]: net.minecraft.server.v1_8_R1.ExceptionWorldConflict: The save for world located at ./bw_goldrush is being accessed from another location, aborting
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:72)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.World.checkSession(World.java:2786)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:131)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:249)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:357)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.WorldServer.doTick(WorldServer.java:221)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:756)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[18:35:10 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[18:35:10 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Granik24** [comment]
I have console spams too: http://pastebin.com/WY8VDWvC
