### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by PatrikCZ** [Yannici/bedwars-reloaded#69]
[12:14:52] [Server thread/ERROR]: Could not load 'plugins\bv.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `io.github.yannici.bedwars.Main'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[server.jar:git-Spigot-1554]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-1554]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Spigot-1554]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-Spigot-1554]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [server.jar:git-Spigot-1554]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [server.jar:git-Spigot-1554]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [server.jar:git-Spigot-1554]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-Spigot-1554]
Caused by: java.lang.ClassNotFoundException: io.github.yannici.bedwars.Main
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[server.jar:git-Spigot-1554]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:83) ~[server.jar:git-Spigot-1554]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:61) ~[server.jar:git-Spigot-1554]
	... 7 more

**Comment by Granik24** [comment]
Hehe, do you implement plugin.yml to your jar?

**Comment by PatrikCZ** [comment]
Yes, you can send me the file in JAVA I do not know anymore Council

**Comment by Yannici** [comment]
Sorry, no support for non-released jar files!

**Comment by PatrikCZ** [comment]
It's the plugin I can not put into the jar file?

**Comment by Yannici** [comment]
And this plugin isn't released, yet,  so be patient or use eclipse to compile it by yourself!

**Comment by PatrikCZ** [comment]
I'm trying to eclipse all the time and this does not work for me I'm going zavama that you sent me a jar of the affected files plugin

**Comment by Yannici** [comment]
Then you're doing something wrong-

**Comment by PatrikCZ** [comment]
Please send me the java file and put it somewhere to download

**Comment by Yannici** [comment]
Didn't you read what I wrote??? Theres no release yet!!!

**Comment by PatrikCZ** [comment]
omg I understand you!

**Comment by Yannici** [comment]
So I won't upload a jar for download. I will send it to you personally at spigot in some minutes.

**Comment by PatrikCZ** [comment]
ok but please šup for me to rush

**Comment by PatrikCZ** [comment]
a spigot on my name: petrick_CZ
